export const title = "GALERIE PHOTO"
export const galleryItems = [
    {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/06/IMG_0206/2970170769.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
    },
    {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/02/3DW_130/3577911815.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
    },
    {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/02/IMG_0095/1484819242.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
      },
     {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/06/IMG_0206/2970170769.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
    },
    {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/02/3DW_130/3577911815.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
    },
    {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/02/IMG_0095/1484819242.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
      },
        {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/06/IMG_0206/2970170769.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
    },
    {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/02/3DW_130/3577911815.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
    },
    {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/02/IMG_0095/1484819242.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
      },
     {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/06/IMG_0206/2970170769.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
    },
    {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/02/3DW_130/3577911815.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
    },
    {
      title: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      link: 'https://legrandunivers.ma/galerie/gallery/plongez-avec-nous-dans-la-magie-de-la-nuit-sacree-du-ramadan',
      imageSrc: 'https://legrandunivers.ma/wp-content/uploads/cache/2023/02/IMG_0095/1484819242.jpg',
      imageAlt: 'Plongez avec nous dans la magie de la nuit sacrée du Ramadan',
      imageWidth: 300,
      imageHeight: 400,
      numImages: 129,
    },
];